---
title: Infosexy
baseline: Making InfoSec cooler, one pun at a time.
description: Making InfoSec cooler, one pun at a time.
baseurl: "/"
canonicalurl: true
keywords:
- InfoSec
- Information Security
- Infosexy
author: Yash
date:
  format: j F Y
  timezone: Europe/Paris
theme:
- hyde
- netlify
- netlify-cms
hyde:
  sidebar:
    sticky: true
  theme: ''
  reverse: false
